apiVersion: v1
kind: Service
metadata:
  name: scalar-re
  namespace: scalar-re
  labels:
    app: scalar-re
spec:
  type: LoadBalancer
  selector:
    app: scalar-re
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
