{
 "title": "RE",
 "tags": [ "scalar-re" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "scalar_re_messages_transferred_total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(scalar_re_messages_transferred_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "tomcat_connections_current_connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "tomcat_connections_current_connections",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "scalar_re_destination_active_workers",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "scalar_re_destination_active_workers",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "rate(tomcat_global_request_seconds_count[1m])",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(tomcat_global_request_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "scalar_re_destination_queue_size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "scalar_re_destination_queue_size",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "scalar_re_transfer_latency_seconds",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "scalar_re_transfer_latency_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "scalar_re_polled_records_count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "targets": [
    { "expr": "scalar_re_polled_records_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "system_cpu_usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "targets": [
    { "expr": "system_cpu_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "scalar_re_messages_transferred_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(rate(scalar_re_messages_transferred_total[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (destination) (rate(scalar_re_messages_transferred_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "sum by (event_type) (rate(scalar_re_tx_rollback_total[1m]))",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "sum by (event_type) (rate(scalar_re_tx_rollback_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WARN|ERROR",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "{compose_service=~\"re-.*|scalar-re\"} |~ \" (WARN|ERROR) \"      "
    }
   ]
  },
  {
   "title": "Exception",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "{compose_service=~\"re-.*|scalar-re\"} |~ \"Exception|Caused by\"    "
    }
   ]
  },
  {
   "title": "Transfer error",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "{compose_service=~\"re-.*|scalar-re\"} |= \"Transfer error\"  "
    }
   ]
  },
  {
   "title": "Transfer conflict",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "{compose_service=~\"re-.*|scalar-re\"} |= \"Transfer conflict\"   "
    }
   ]
  },
  {
   "title": "Moved to DLQ",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "{compose_service=~\"re-.*|scalar-re\"} |= \"Moved to DLQ\"    "
    }
   ]
  },
  {
   "title": "Poison message",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "{compose_service=~\"re-.*|scalar-re\"} |= \"Poison message\"   "
    }
   ]
  }
 ]
}